require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

# Enable modular headers globally
# use_modular_headers!
use_frameworks! :linkage => :static

prepare_react_native_project!

flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
# flipper_config = FlipperConfiguration.disabled

target 'MyProject' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Uncomment Firebase pods if required
  # pod 'Firebase/Core', :modular_headers => true
  # pod 'Firebase/Messaging', :modular_headers => true
  # pod 'Firebase/Auth', :modular_headers => true
  # pod 'Firebase/Storage', :modular_headers => true
  # pod 'Firebase/Firestore', :modular_headers => true
  

  # Uncomment gRPC and BoringSSL-GRPC pods if required
  # pod 'gRPC-Core', :modular_headers => true
  # pod 'BoringSSL-GRPC', :modular_headers => true


  target 'MyProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      :mac_catalyst_enabled => false
    )
    
    __apply_Xcode_12_5_M1_post_install_workaround(installer)


    # Start add for xcode 15
    installer.pods_project.targets.each do |target|
      if target.name == 'Flipper'
        file_path = 'Pods/Flipper/xplat/Flipper/FlipperTransportTypes.h'
        contents = File.read(file_path)
        unless contents.include?('#include <functional>')
          File.chmod(0755, file_path)
          File.open(file_path, 'w') do |file|
            file.puts('#include <functional>')
            file.puts(contents)
          end
        end
      end
    end
    # End for xcode 15

  end
end
